### ISSUE TITLE
switch-case indentation

### ISSUE THREAD

**Issue by mlopezgva** [2072/vim-syntax-for-PHP#1]
Hello!

I'd like to ask what should I change in this file so I can get an indentation for the witch construct like this:

``` php
// [ ... ]
    switch($var) {
        case 'a':
            do_something();
        break;
        case 'b':
            do_whatever_else();
        break;
        default:
            default_action();
        break; // optional
    }
```

As you can see, the `break` statement indents back to the `case` level, which is consistent with the fact that it "ends" the _case block_. It is also similar to other php syntaxes: `if (): / else: / endif;` or `for (): / endfor;`, etc.

I know this is not "standard" (PSRx), and I'm thinking about proposing it :), but since it is not, I would like to modify the syntax file to get this indentation scheme.

May you help me on this? I'm not proficient in vim script (I'm learning, just wrote a function 2 weeks ago :D), much less syntax files. O:)

Thank you.

**Comment by 2072** [comment]
Hi,

This has nothing to do with the syntax file but with the [indentation script](https://github.com/2072/PHP-Indenting-for-VIm) which is very complex and difficult to modify. You must be very familiar with advanced regular expressions to understand how it works.
The change you want might not be difficult to implement (I might be wrong though). What you want is basically to indent `break` just like `case` and `default` are indented. So I would first check how the later are dealt with and try to see if I could just include `break` in the logic... but watch for side effects and carefully check everything that mentions `break`.

**Comment by mlopezgva** [comment]
Sorry, I figured it out (it should be the indent file) two days after... I'll try to talk with the indent maintainer to get advice. It may end that it will not be so difficult to "indent out" all the rules related to the "break" sentence.
You may close this issue. Thank you.

**Comment by 2072** [comment]
I am the PHP indent script maintainer^^
